repos:
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
- repo: https://github.com/sqlalchemyorg/zimports/
  rev: v0.6.1
  hooks:
  - id: zimports
    args: [ "--style", "pycharm" ]
