#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause
import argparse
import sys

import cdinfo
import detect
import util
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QApplication


def main(argv):
    parser = argparse.ArgumentParser(description="fripper - CD ripper")
    parser.add_argument(
        "--discid",
        "-d",
        dest="discid",
        default=None,
        metavar="ID",
        help="debug mode; runs as if the given disc was inserted, fakes commands",
    )
    args = parser.parse_args(argv[1:])

    discid = args.discid
    if not discid:
        discid = detect.get_disc_id()

    disc = detect.get_cd_info(discid)

    app = QApplication(argv)
    app.setWindowIcon(QIcon(util.icon("fripper.png")))

    info = cdinfo.InfoDialog(disc)
    info.exec_()

    sys.exit(0)


if __name__ == "__main__":
    main(sys.argv)
