#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause
import argparse
import sys

import detect
import ripper
import util
from PyQt5.QtCore import QTimer
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QApplication


def main(argv):
    parser = argparse.ArgumentParser(description="fripper - CD ripper")
    parser.add_argument(
        "--discid",
        "-d",
        dest="discid",
        default=None,
        metavar="ID",
        help="debug mode; runs as if the given disc was inserted, fakes commands",
    )
    parser.add_argument(
        "--debug",
        dest="debug",
        action="store_true",
        default=False,
        help="debug mode; runs with pre-baked disc info (skips musicbrainz)",
    )
    args = parser.parse_args(argv[1:])

    if args.debug:
        import debug

        disc = debug.DISC
    else:
        discid = args.discid
        if not discid:
            discid = detect.get_disc_id()

        disc = detect.get_cd_info(discid)

    app = QApplication(argv)
    app.setWindowIcon(QIcon(util.icon("fripper.png")))
    QTimer.singleShot(0, lambda: ripper.rip(app, disc))

    ec = app.exec_()
    util.SETTINGS.sync()
    sys.exit(ec)


if __name__ == "__main__":
    main(sys.argv)
