#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause
import argparse
import sys

import detect
import ripper
import util
from PyQt5.QtCore import QTimer
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QApplication


def rip(app, disc, discid):
    if not disc:
        detector = detect.DetectionDialog(discid=discid)
        detector.exec_()
        if not detector.disc:
            app.quit()
            return
        disc = detector.disc

    try:
        ripper.rip(app, disc)
    except Exception as e:
        util.show_error(e)


def main(argv):
    parser = argparse.ArgumentParser(description="fripper - CD ripper")
    parser.add_argument(
        "--discid",
        "-d",
        dest="discid",
        default=None,
        metavar="ID",
        help="debug mode; runs as if the given disc was inserted, fakes commands",
    )
    parser.add_argument(
        "--debug",
        dest="debug",
        action="store_true",
        default=False,
        help="debug mode; runs with pre-baked disc info (skips musicbrainz)",
    )
    args = parser.parse_args(argv[1:])

    disc = None
    if args.debug:
        import debug

        disc = debug.DISC
        util.TEST_MODE = True
    else:
        discid = args.discid
        if discid:
            util.TEST_MODE = True

    app = QApplication(argv)
    app.setWindowIcon(QIcon(util.icon("fripper.png")))
    QTimer.singleShot(0, lambda: rip(app, disc, discid))

    ec = app.exec_()
    util.SETTINGS.sync()
    sys.exit(ec)


if __name__ == "__main__":
    main(sys.argv)
